safe_characters = "@abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_: /"
sql_user_name = "%{User-Name}"

event_timestamp_epoch = "%{%{integer:Event-Timestamp}:-%l}"

event_timestamp = "FROM_UNIXTIME(${event_timestamp_epoch})"

class {
	column_name =	# ", class"
	packet_xlat =	# ", '%{Class}'"
	reply_xlat =	# ", '%{reply:Class}'"
}

client_query = "\
	SELECT id, nasname, shortname, type, secret, server \
	FROM ${client_table}"

post-auth {

	query =	"\
		INSERT INTO ${..postauth_table} \
			(username, pass, reply, authdate ${..class.column_name}) \
		VALUES ( \
			'%{SQL-User-Name}', \
			'%{%{User-Password}:-%{Chap-Password}}', \
			'%{reply:Packet-Type}', \
			'%S.%M' \
			${..class.reply_xlat})"
}
