
client REF1234 { ipaddr = 1.1.1.1 , secret = secret }
client REFtestclient { ipaddr = 123.231.12.55 , secret = secret }
client REFtestclient02 { ipaddr = 124.43.25.139 , secret = testing123 }
#client REFlocal { ipaddr = 127.0.0.1 , secret = testing123 }
#client REFlocal3 { ipaddr = 97.74.236.76 , secret = testing123 }
client REFlocal2 { ipaddr = 97.47.236.76 , secret = testing123 }
client REFLB { ipaddr = 113.59.205.147 , secret = secret }
#client REFTEST1 { ipaddr = 3.87.58.132 , secret = testing123 , virtual_server = gpon , require_message_authenticator = no , limit_proxy_state = auto } 
client REFDEFAULT { ipaddr = 0.0.0.0/0 , secret = testing123 , require_message_authenticator = no , limit_proxy_state = auto }
client REFVSZ {ipaddr = 216.234.148.172 , secret = vsztesting123 }
client REFVSZ {ipaddr = 3.19.0.0 , secret = testing123 }
client REFCISCO {ipaddr = 209.206.60.119 , secret = testing123 }
